axelarnetwork/axelarjs

- packages/api/src/gmp/types.ts
- packages/core/src/index.ts
- packages/transaction-recovery/package.json
- packages/transaction-recovery/src/addGas.spec.ts
- packages/transaction-recovery/src/addGas.ts
- packages/transaction-recovery/src/cosmosSigner/index.ts
- packages/transaction-recovery/src/cosmosSigner/offlineSigner.ts
- packages/transaction-recovery/src/cosmosSigner/signer.ts
- packages/transaction-recovery/src/services/index.ts
- pnpm-lock.yaml
more details here: https://axelarnetwork.atlassian.net/browse/AXE-1714
> feat: 'working' implementation of addgas complete

- .changeset/cool-pugs-vanish.md
- packages/evm/bin/cli.mjs
- packages/evm/scripts/codegen-its.sh
- packages/evm/scripts/codegen.ts
```
Usage: codegen [options]
Options:
--src <src>         The folder where the contracts are located (required)
--out <out>         The folder where the generated files will be written (required)
--exclude <exclude> Comma separated list of glob patterns to exclude (optional, default: [])
--flatten           Whether to flatten the output folder structure (optional, default: false)
--filecase          The case of the generated file names (optional, default: pascal)
--foldercase        The case of the generated folder names (optional, default: pascal)
--index             Whether to generate index files (optional, default: false)
--client            Path to the PublicClient module (optional, default: "@axelarjs/evm")
```
> feat: more codegen options & ability to generate index files

- packages/api/package.json
- packages/api/src/axelar-config/types.ts
- packages/api/src/deposit-address/isomorphic.ts
- packages/api/src/deposit-service/client.spec.ts
- packages/api/src/deposit-service/client.ts
- packages/api/src/deposit-service/index.ts
- packages/api/src/deposit-service/isomorphic.ts
- packages/api/src/deposit-service/types.ts
- packages/api/src/index.ts
- packages/core/src/index.ts
- packages/cosmos/package.json
- packages/cosmos/src/stargate/spec/constants.ts
- packages/cosmos/src/stargate/spec/queryClient.spec.ts
- packages/cosmos/src/stargate/spec/stargateClient.spec.ts
- packages/deposit-address/package.json
- packages/deposit-address/src/get-deposit-address/client.ts
- packages/deposit-address/src/get-deposit-address/helpers/depositService.spec.ts
- packages/deposit-address/src/get-deposit-address/helpers/depositService.ts
- packages/deposit-address/src/get-deposit-address/helpers/getDepositAddressFromAxelarNetwork.ts
- packages/deposit-address/src/get-deposit-address/helpers/index.ts
- packages/deposit-address/src/get-deposit-address/helpers/validation.ts
- packages/deposit-address/src/get-deposit-address/isomorphic.spec.ts
- packages/deposit-address/src/get-deposit-address/isomorphic.ts
- packages/deposit-address/src/get-deposit-address/types.ts
- pnpm-lock.yaml
This PR added support for wrap/unwrap deposit address generation.
- Added `getNativeWrapDepositAddress` API
- Added `getNativeUnwrapDepositAddress` API
- Renamed `getDepositAddress` to `getLinkedDepositAddress`
- Added the new `getDepositAddress` API. This function will return the deposit address based on three scenarios:
- The source token is native token, then this function returns deposit address from the `getNativeWrapDepositAddress` function.
- The source token is not native token and the associated `asset` on the destination chain has `isERC20WrappedNativeGasToken = true`, then this function will return the linked deposit address where the destination address for linked deposit address is unwrap deposit address. (there're two addresses generation)
- The source token is not native …
> feat: add deposit service

- packages/api/src/axelar-query/utils/bigint.spec.ts
- packages/api/src/axelar-query/utils/bigint.ts
This PR fixes an error `RangeError: Division by zero` when trying to estimate gas for tx that sending from `evm chain` to `cosmos chain`
> fix: "RangeError: Division by zero" error

- packages/api/src/axelar-query/isomorphic.ts
Removed default value for `gasLimit`. If specified, it should be greater than the minimum value (21k gas).
> chore: remove default gasLimit from `estimateGasFee`

- apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx
[AXE-3057](https://axelarnetwork.atlassian.net/browse/AXE-3057?atlOrigin=eyJpIjoiMTM0MmM0MWI3YmE2NDVhMWFlZGYwMGU3YzkxMTc3MzMiLCJwIjoiaiJ9)
Disable send button when user has insufficient gas instead of just changing the text which does nothing when click.
[AXE-3057]: https://axelarnetwork.atlassian.net/browse/AXE-3057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: disable button when user has insufficient gas

- apps/maestro/src/features/ManageInterchainToken/actions/mint/MintInterchainToken.tsx
[AXE-3058](https://axelarnetwork.atlassian.net/browse/AXE-3058?atlOrigin=eyJpIjoiOWIwZGM4ZTU1MzAzNGI0MWE1NzlhZmE5ZjhkMjEyYTEiLCJwIjoiaiJ9)
Fix error when trying to mint token with amount with floating points. `parseUnits` function from viem basically handles this.
[AXE-3058]: https://axelarnetwork.atlassian.net/browse/AXE-3058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: floating points error

- apps/maestro/src/features/Transactions/Transactions.tsx
- apps/maestro/src/ui/compounds/GMPTxStatusMonitor/GMPTxStatusMonitor.tsx
Right now, the progress bars appear if current num confirmations < expected. Also adding a condition to hide the progress bar if the tx has already been confirmed.
> chore: add condition to showing finality progess bar

- apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
this fix addresses the following steps to reproduce:
1. for this token page: https://testnet.interchain.axelar.dev/avalanche/0x88a0cccD4Bcfd55Ff9D11f68023acF7192bf6694, you see that address on polygon is 0x7748FEAD09B1aD139Fe979Ed54E8652BC811A13d
2. open a new window and switch your wallet to polygon, then search for 0x7748FEAD09B1aD139Fe979Ed54E8652BC811A13d
3. you'll see that there isn't an origin token listed, and you can't transfer to any other chain.
> chore: fix search results to center lookup token to origin token

- .changeset/lucky-coins-explode.md
* generated from running `npm run changeset` from the root directory of the repo
* from the `lucky-coins-explode.md` file, manually entered all changes by looking at this diff: https://github.com/axelarnetwork/axelarjs/compare/%40axelarjs/maestro%400.3.4...main
> chore: its portal changelog

- .changeset/orange-laws-hang.md
- packages/api/package.json
- pnpm-lock.yaml
when running @axelar/api from a script, it complained that axelar/utils was not found. so making it an explicit dependency of the package
> chore: axelar api dependencies

- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx
[AXE-3626](https://axelarnetwork.atlassian.net/browse/AXE-3626)
Closes https://github.com/axelarnetwork/axelarjs/issues/275
The popup shows when the cursor is hovering over the link. I temporarily simply added the link here for now. I'll think more about better places since there're more cta to be added.
[AXE-3626]: https://axelarnetwork.atlassian.net/browse/AXE-3626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add whitelist token on squid link

- apps/maestro/src/lib/utils/gform.ts
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/index.tsx
- Excluded src chain from being auto-filled in `Chains to claim token ownership on` section (the image below)
- Mapped src chain name to the form value
> chore: exclude src chain from "chains to claim token ownership" field

- apps/maestro/src/config/dex.ts
quick fix for wrong uniswap logo
> chore: fix uniswap logo

- .changeset/eight-nails-hunt.md
- packages/api/src/gmp/types.ts
- packages/transaction-recovery/src/query-transaction-status/client.ts
- packages/transaction-recovery/src/query-transaction-status/index.ts
- packages/transaction-recovery/src/query-transaction-status/isomorphic.spec.ts
- packages/transaction-recovery/src/query-transaction-status/isomorphic.ts
- packages/transaction-recovery/src/query-transaction-status/types.ts
[AXE-4225](https://axelarnetwork.atlassian.net/browse/AXE-4225)
Migrated the `queryTransactionStatus` function from SDK v1.
There're some difference between response in v1 and v2 as follows
**✅ Success:**
```typescript
{
status: string,
error: object,
timeSpent: object,
gasPaidInfo: object,
callTx: object,
executed: object,
expressExecuted: object,
approved: object
};
```
**❌ Fail**
```typescript
{
status: "cannot_fetch_status"
}
```
**✅ Success**
```typescript
{
success: true;
data: {
status: GMPTxStatus;
error?: QueryTransactionStatusError | undefined;
timeSpent: SearchGMPTimespent;
gasPaidInfo: {
status: SearchGMPGasStatus;
details: SearchGMPGasPaid;
};
callTx: SearchGMPCall;
executed?: SearchGMPExecuted | undefined;
expressExecuted?: SearchGMPExpressExecuted | undefined; …
```
> feat: add query transaction status

- .changeset/forty-birds-cheer.md
- packages/api/src/axelar-query/utils/bigint.spec.ts
- packages/api/src/axelar-query/utils/bigint.ts
Fix math rounding issue for `estimateGasFee` api. This issue was detected by running estimateGasFee test script where it tried to fetch gas fee from 3 directions which are: `cosmos -> evm`, `evm -> cosmos`, and `evm -> evm`. The issue seems to be resolved with this fix.
> chore: fix estimateGasFee math rounding issue

- .changeset/short-jeans-prove.md
- apps/maestro/src/server/routers/erc20/getERC20TokenDetails.ts
- apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
- apps/maestro/src/services/erc20/hooks.ts
Fix long loading times when searching for an address.
Set `retry: false` for TRPC query to get ERC20 token info. The query was being executed three times and each of these took a long time to complete, with one call being enough to get the same result.
Make the RPC calls to all chains concurrent for a much faster response.
Search for tokens, especially tokens that do not exist, and the error should come much earlier than in production.
https://github.com/user-attachments/assets/953e9b39-e4d9-4cb9-ad0a-7b93d9f16407
The production app can take up to 35-45x longer to complete the search than the new version.
> fix: search tokens loading times

- .changeset/little-brooms-sparkle.md
- apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
~~Currently, the token details page cannot be loaded successfully. It seems like this https://github.com/axelarnetwork/axelarjs/pull/418 has some unexpected side-effects. This PR reverted the `scanChains` function to the original code, before the changes were introduced.~~
It's just because we forgot to return the value out of the function...
> chore: fix the token details doesn't load properly

- .changeset/wild-adults-attack.md
- apps/maestro/src/server/routers/interchainToken/index.ts
- apps/maestro/src/server/routers/interchainToken/recoverDeploymentMessageIdByTokenId.ts
- apps/maestro/src/services/db/postgres/MaestroPostgresClient.ts
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx
Recover the deployment message id when visiting the token details page if missing.
- Create query to recover message id by token id. 
- Check if the id is missing in every visit to token details page and try to recover it.
Please delete options that are not relevant.
Go to the details page of a token with a missing deployment message it, check it shows as unregistered ITS token and wait for it to update.
You can achieve this by deleting the message id from the db for an existing token.
https://github.com/user-attachments/assets/25b9ca33-fe5d-4d00-96ab-a21cfb2f6225
Check how the token with the missing deployment message id updates automatically in the details page after some seconds.
> feat: recover deployment message id when visiting token details page

- .changeset/orange-dodos-sparkle.md
- apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
- [ITS-453](https://github.com/axelarnetwork/axelarjs/issues/453)
Fixed an issue where searching a token without specifying chain id was failing.
The issue was that the query was returning `undefined` and not `null` as expected by the code, returning only the result of the first chain searched.
When the chain was specified, the query was looking for the specified chain first, that's what made it work.
Please delete options that are not relevant.
Run the app and go to `http://localhost:3000/api/interchain-token/search?tokenAddress=0x0c66d591d1ff5944A44aebB65c33f6B6e82a124F`
The same query without the change should fail.
https://github.com/user-attachments/assets/c6a91790-ffee-4523-85a8-714581aa27a3
Closes #453
> fix: search interchain tokens query searching only first chain

- apps/maestro/src/services/interchainToken/hooks.ts
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/index.tsx
https://axelarnetwork.atlassian.net/browse/AXE-5295
This PR fixes the token details page doesn't render correctly when user searched with the remote interchain token address.
> fix: cannot find remote interchain token

- apps/maestro/package.json
- apps/maestro/src/config/env.ts
- apps/maestro/src/config/evm-chains.ts
- apps/maestro/src/features/InterchainTokenDeployment/hooks/useDeployAndRegisterRemoteInterchainTokenMutation.ts
- apps/maestro/src/features/suiHooks/useDeployToken.ts
- apps/maestro/src/pages/_app.tsx
- apps/maestro/src/server/context.ts
- apps/maestro/src/server/routers/sui/config/devnet-amplifier.json
- apps/maestro/src/server/routers/sui/index.ts
- apps/maestro/src/server/utils.ts
- apps/maestro/src/services/axelarjsSDK/index.ts
- apps/maestro/src/services/axelarscan/index.ts
This PR supports `devnet-amplifier` env. 
To run the web server, the `NEXT_PUBLIC_NETWORK_ENV="devnet-amplifier"` env needs to be set. 
It also supports multiple token deployments from sui to evm chains in this pr as well.
> feat: support devnet amplifier

- apps/maestro/package.json
- apps/maestro/src/features/CanonicalTokenDeployment/steps/deploy-and-register/DeployAndRegister.state.ts
- apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.state.ts
- apps/maestro/src/lib/utils/bigint.ts
- apps/maestro/src/server/routers/sui/index.ts
- apps/maestro/src/services/axelarjsSDK/index.ts
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx
- pnpm-lock.yaml
- Removed the hardcode gas fee between sui and evm chains 
- Integrated the estimate gas fee api from `axelarjs-sdk` to support ITS hub. 
- Fixed the hardcoded decimals (18) when renders total gas fee depends on the decimals from `useBalance` hook
> feat: integrate estimate gas fee api

- apps/maestro/src/server/routers/gmp/getTransactionStatusOnDestinationChains.ts
Fixes an issue where the destination chain becomes undefined after initiating a token transfer transaction from Flow.
- The backend incorrectly uses 'axelar' as the destination chain ID
- Token transfers from Flow are 2-hop transactions (Flow → Axelar → Final Destination)
- Using 'axelar' as the destination chain ID is invalid since it's only an intermediary
- Read the correct destination chain ID from the `InterchainTransfer` event
- Utilize the existing searchGMP response to retrieve this information, which we already use for transaction status monitoring
> fix: undefined chain after token transfer from flow

- apps/maestro/src/features/InterchainTokenDeployment/hooks/useDeployAndRegisterRemoteInterchainTokenMutation.ts
- apps/maestro/src/features/ManageInterchainToken/actions/transfer-operatorship/TransferInterchainTokenOperatorship.tsx
- apps/maestro/src/features/ManageInterchainToken/hooks/useTransferTreasuryCapMutation.ts
- apps/maestro/src/features/RegisterRemoteTokens/RegisterRemoteTokens.tsx
- apps/maestro/src/features/RegisterRemoteTokens/hooks/useRegisterRemoteInterchainTokenOnSui.ts
- apps/maestro/src/features/RegisterRemoteTokens/hooks/useRegisterRemoteInterchainTokens.ts
- apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx
- apps/maestro/src/server/routers/erc20/getERC20TokenBalanceForOwner.ts
- apps/maestro/src/server/routers/gmp/getTransactionStatusesOnDestinationChains.ts
- apps/maestro/src/server/routers/interchainToken/recordInterchainTokenDeployment.ts
- apps/maestro/src/server/routers/interchainToken/recordRemoteTokensDeployment.ts
- apps/maestro/src/server/routers/interchainToken/updateSuiRemoteTokenAddresses.ts
- apps/maestro/src/server/routers/sui/index.ts
- apps/maestro/src/server/routers/sui/utils/txUtils.ts
- apps/maestro/src/server/routers/sui/utils/utils.ts
- apps/maestro/src/services/gmp/hooks.ts
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx
This PR supports token deployment from the token details page and fix various issues related to token transfer
- Support token deployment from the token details page [AXE-7558](https://axelarnetwork.atlassian.net/browse/AXE-7658)
- Fix Sui balance doesn't show when Sui is the remote chain [AXE-7657](https://axelarnetwork.atlassian.net/browse/AXE-7657)
- Validate Sui address when transfer the token [AXE-7664](https://axelarnetwork.atlassian.net/browse/AXE-7664)
- Don't prefill destination address when the connected wallet address is not compatible with destination chain [AXE-7670](https://axelarnetwork.atlassian.net/browse/AXE-7670)
- Fix wrong sui token decimals [AXE-7671](https://axelarnetwork.atlassian.net/browse/AXE-7671)
- Disable autocomplete on destination address input in transfer …
> fix: token deployment and token transfer in token details

- .changeset/bright-spiders-wink.md
- apps/maestro/src/server/routers/interchainToken/getInterchainTokenBalanceForOwner.ts
- apps/maestro/src/server/routers/interchainToken/updateSuiRemoteTokenAddresses.ts
- apps/maestro/src/server/routers/sui/index.ts
- apps/maestro/src/server/routers/sui/utils/txUtils.ts
- apps/maestro/src/server/routers/sui/utils/utils.ts
- apps/maestro/src/services/db/postgres/MaestroPostgresClient.ts
- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx
- packages/api/src/axelar-config/types.ts
https://axelarnetwork.atlassian.net/browse/AXE-8025
Replaced hardcoded static config URL with `axelarConfigs` function from context, leveraging caching and automatic environment handling. Plus, this pr also fix that some sui functions still fetch the old sui chain configs from the Koyeb url.
> chore: fix hardcoded axelar chain confiig

- apps/maestro/src/features/RegisterRemoteTokens/RegisterRemoteTokens.tsx
- apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
https://axelarnetwork.atlassian.net/browse/AXE-8106
This PR fixes the bug where the destination sui chain doesn't move from pending to registered state. 
Another change is to wrap the whole `handleClick` function for submit additional token register chain button into the `try-catch` block to make sure that whatever errors that throws out of the function will be handled gracefully.
it happens when the tx for token register at the origin chain and the tx for remote token register are different. when the destination chain is sui, it uses the `deploymentMessageId` to search for executed tx hash at sui chain. however, there’re two types of `deploymentMessageId` in this case which are:
- `deploymentMessageId`  for token register at the source chain which is a non-gmp call
- …
> chore: fix sui deployment

- packages/api/src/axelar-config/isomorphic.ts
We don't need to separate the url for `devnet-amplifier` since both `1.x` and `1.0.x` include `sui-2` now.
> chore: update axelar configs url devnet

- apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx
Fixes a bug where when closing and reopening the transfer modal, the address is not being set and for evm->evm transfers, you can't edit the field so there's nothing you can do.
> fix: transfers modal set address for evm

- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx
The updated address format lets us navigate to the coin page
> chore: fix sui scanner url

- apps/maestro/src/config/env.ts
- apps/maestro/src/services/axelarjsSDK/index.ts
- apps/maestro/src/services/db/postgres/MaestroPostgresClient.ts
Fixes token query failure due to chain ID case sensitivity (e.g., "polygon" vs. "Polygon")
> fix: use ilike for chain id and token address queries

- .changeset/chatty-cherries-fail.md
- apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
- packages/core/src/index.ts
Fix the token details page cannot render stellar as a remote registered chain properly due to invalid rpc url
> fix: use chain config for stellar rpc url

- apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx
undefined token id values were being read and caused an error on the homepage
> chore: prevent reading undefined tokenid for token images

- apps/maestro/src/features/InterchainTokenDeployment/steps/token-details/TokenDetails.tsx
This PR implements some Hedera specific rules on new Interchain Token creation:
- token must be mintable
- token initial supply must be 0
The affected form fields are removed from the UI and their value is set programatically.
It also adds an informational note on the token creation modal. Some UI fixes also applied.
> ITS-69 Add Hedera specific rules in token creation
