axelarnetwork/axelarjs

apps/maestro/src/features/RecentTransactions/RecentTransactions.tsx
apps/maestro/src/features/RecentTransactions/RecentTransactionsList.tsx
apps/maestro/src/features/SearchInterchainToken/SearchInterchainToken.tsx
apps/maestro/src/pages/index.tsx

@alanrsoares just some small styling suggestions. take it or leave it?

chore: styling updates to maestro

---

apps/maestro/src/features/Transactions/Transactions.tsx
apps/maestro/src/services/gmp/hooks.ts
apps/maestro/src/ui/compounds/GMPTxStatusMonitor/GMPTxStatusMonitor.tsx

This PR refactors toast ui for tracking transaction status to be more robust as @alanrsoares has designed below
| Old | New |
|-----|-----|
|![image](https://github.com/axelarnetwork/axelarjs/assets/78221556/3acdb867-2426-4101-adc3-bfc76ba50aca)|![image](https://github.com/axelarnetwork/axelarjs/assets/78221556/a86d6678-1ea1-4576-a321-124c876bcaf9)|

feat: refactor toast ui for tx status tracking

---

apps/maestro/src/features/CanonicalTokenDeployment/CanonicalTokenDeployment.tsx
apps/maestro/src/server/context.ts
apps/maestro/src/server/routers/_app.ts
apps/maestro/src/server/routers/axelarConfigs/getChainConfigs.ts
apps/maestro/src/server/routers/axelarConfigs/index.ts
apps/maestro/src/services/axelarConfigs/hooks.ts

feat: restricting gateway tokens

---

apps/maestro/src/features/InterchainTokenList/RegisteredInterchainTokenCard.tsx
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.spec.tsx
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx

Just change text from "send" to "transfer" in the following pages:

fix: update text from send to transfer for consistency

---

apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

| Before | New |
|--------|-----|
| ![before](https://github.com/axelarnetwork/axelarjs/assets/78221556/fdf92a42-e827-41d7-a01c-9e12d3722b4c)|![after](https://github.com/axelarnetwork/axelarjs/assets/78221556/c42a7722-8944-450e-a0fe-aad4b1e107b4)|

fix: token symbol overlap the title bar

---

apps/maestro/src/features/InterchainTokenList/RegisteredInterchainTokenCard.tsx

**WIP**
- ~~When open the Modal, the button is shifted to the left. I'm still investigating the root cause.~~ done

fix: remove setting icon with text

---

apps/maestro/src/features/ManageInterchainToken/ManageInterchainToken.tsx

Update the following texts:
- transfer Operatorship -> Transfer Rate Limit Manager
- Register interchain tokens -> Register Chains

fix: improve text

---

apps/maestro/src/features/SendInterchainToken/SendInterchainToken.spec.tsx
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.state.ts
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx

feat: add token symbol on Transfer page

---

apps/maestro/src/server/routers/erc20/getERC20TokenDetails.ts

quick hack to override symbol for OP, should refactor later

chore: add symbol override

---

apps/maestro/.env.example
apps/maestro/src/config/env.ts
apps/maestro/src/pages/competition/index.tsx
apps/maestro/src/ui/compounds/GMPTxStatusMonitor/GMPTxStatusMonitor.tsx
packages/ui/src/components/Progress/Progress.spec.tsx
packages/ui/src/components/Progress/Progress.stories.tsx
packages/ui/src/components/Progress/Progress.tsx
packages/ui/src/components/Progress/index.ts
packages/ui/src/components/index.ts

feat: make competition configurable

---

apps/maestro/src/features/SendInterchainToken/SendInterchainToken.state.ts
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx
apps/maestro/src/services/db/postgres/MaestroPostgresClient.ts
packages/ui/src/components/icons/lucide/index.ts

feat: add sendToken finality time disclaimer

---

apps/maestro/src/pages/competition/index.tsx

[AXE-3071](https://axelarnetwork.atlassian.net/browse/AXE-3071?atlOrigin=eyJpIjoiMzU1NzAyNDQ0NzljNDA1M2E2MjI2ZmYyYWJjMDYwODYiLCJwIjoiaiJ9)
Add intro text in the competition page
[AXE-3071]: https://axelarnetwork.atlassian.net/browse/AXE-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add competition intro text

---

apps/maestro/src/features/CanonicalTokenDeployment/steps/deploy-and-register/DeployAndRegister.tsx
apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.tsx
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.spec.tsx
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx

feat: display modal errors as alerts

---

apps/maestro/src/features/CanonicalTokenDeployment/CanonicalTokenDeployment.tsx
apps/maestro/src/features/CanonicalTokenDeployment/steps/deploy-and-register/DeployAndRegister.state.ts
apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.state.ts
apps/maestro/src/ui/components/EVMChainsDropdown/EVMChainsDropdown.tsx
apps/maestro/src/ui/compounds/MultiStepForm/MultiStepForm.tsx
apps/maestro/src/ui/layouts/Page.tsx
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

Improve chain picker UX when bad chain selected:
Improve gateway token warning:
Improve canonical token language:
Reduce gas multiplier to 1.5 on all cross-chain deployments
Update pre-existing token language:

chore: improve chain picker logic when not connected to a valid chain

---

apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

chore: increase text size of header

---

apps/maestro/src/features/InterchainTokenDeployment/hooks/useDeployAndRegisterRemoteInterchainTokenMutation.ts
apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.tsx

Fix cannot set initial supply with float number

chore:  fix initial supply cannot be a float number

---

apps/maestro/src/features/RegisterRemoteTokens/RegisterRemoteTokens.tsx
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx

feat: add error on deploying add'l tokens when user doesn't have enough gas

---

apps/maestro/src/features/InterchainTokenDeployment/steps/token-settings/TokenSettings.tsx

chore: add warning if fixed supply token has zero initial supply

---

packages/api/src/axelar-query/fee/getL1Fee.ts
packages/api/src/deposit-address/client.spec.ts

chore: fix flaky tests

---

apps/maestro/src/server/routers/gmp/getTopTransactions.ts

The rules of the competition require that the leaderboard only show top transfers during the competition window only for tokens deployed during the window. 
This PR modifies the backend to do that additional filter by first downloading all token deployments and mapping to a set, and then subsequently filtering out the interchain transfers of tokens that appear in that set

chore: backend filter for only tokens deployed during competition window

---

apps/maestro/src/features/InterchainTokenList/RegisteredInterchainTokenCard.tsx
apps/maestro/src/features/InterchainTokenList/types.ts
apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts

feat: add token manager address to each registered card

---

apps/maestro/src/server/routers/gmp/getTopTransactions.ts
packages/api/src/gmp/types.ts

feat: update types in api package for token manager deployment started events
closes #205

feat: add support for custom token indexing

---

apps/maestro/CHANGELOG.md

chore: update changelog with other 0.3.0 features

chore: update changelog with other 0.3.0 features

---

apps/maestro/CHANGELOG.md

chore: add #203 to changelog

---

apps/maestro/src/server/routers/axelarscan/getEVMChainConfigs.ts
apps/maestro/src/services/axelarscan/hooks.ts

fix: use localeCompare to sort chains by name

---

apps/maestro/augmentations.d.ts
apps/maestro/src/lib/polyfills.ts
apps/maestro/src/pages/_app.tsx
apps/maestro/tsconfig.json

fix: polyfill BigInt.prototype.toJSON

---

apps/maestro/src/features/SendInterchainToken/SendInterchainToken.state.ts

fix: eligible target chains state derivation

---

apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts

https://ramdajs.com/docs/#propEq

fix: filter function for originChainConfig

---

apps/maestro/src/features/Transactions/Transactions.tsx

fix: tx status indicator not showing pending tx on click

---

apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

* allow token either token deployer or token operator to update icon
* show indicator next to token icon when there's no icon url set

feat: allow token deployer to update token icon

---

apps/maestro/src/server/utils.ts
packages/api/package.json
packages/api/src/axelar-config/isomorphic.ts
packages/api/src/axelar-config/spec/axelar-config.schema.json
packages/api/src/axelar-config/spec/client.spec.ts
packages/api/src/axelar-config/spec/stub.json
packages/api/src/axelar-config/types.ts
packages/api/tsconfig.json
packages/deposit-address/src/get-deposit-address/helpers/depositService.spec.ts
packages/deposit-address/src/get-deposit-address/helpers/depositService.ts
packages/deposit-address/src/get-deposit-address/helpers/getDepositAddressFromAxelarNetwork.ts
packages/deposit-address/src/get-deposit-address/helpers/validation.ts
packages/deposit-address/src/get-deposit-address/isomorphic.spec.ts
packages/deposit-address/src/get-deposit-address/isomorphic.ts
packages/transaction-recovery/src/cosmos-add-gas/isomorphic.ts
packages/transaction-recovery/src/cosmos-add-gas/types.ts
packages/transaction-recovery/src/evm-add-native-gas/isomorphic.ts
packages/transaction-recovery/src/evm-add-native-gas/lib/helper.ts
pnpm-lock.yaml

new config based on this file: https://github.com/axelarnetwork/chains/blob/feat/config-fixes/configs/mainnet-config-1.x.json

feat: update schema for new axelar-configs schema and updating tests

---

apps/maestro/src/features/CanonicalTokenDeployment/CanonicalTokenDeployment.tsx

found a lingering regression from this recent PR due to change in the schema for the configs: https://github.com/axelarnetwork/axelarjs/pull/280

chore: axelar configs regression

---

apps/maestro/src/ui/layouts/MainLayout/MainLayout.tsx
apps/maestro/src/ui/layouts/MainLayout/MainMenu.tsx

Closes #277 [AXE-3647](https://axelarnetwork.atlassian.net/browse/AXE-3647)
Adds "Report Bug" button at the footer
[AXE-3647]: https://axelarnetwork.atlassian.net/browse/AXE-3647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add report bug button

---

apps/maestro/src/features/SearchInterchainToken/SearchInterchainToken.tsx

Closes #309 
Dark theme:
| Previous | New |
|-----|-----|
| ![image](https://github.com/axelarnetwork/axelarjs/assets/78221556/2b22538e-da55-475b-9373-ba9c775a073e) | <img width="1261" alt="image" src="https://github.com/axelarnetwork/axelarjs/assets/78221556/4397075e-d6df-434f-891a-5bae2fdee6ab"> |
Light theme:
| Previous | New |
|-----|-----|
| <img width="1029" alt="image" src="https://github.com/axelarnetwork/axelarjs/assets/78221556/9ee6d946-3e1c-4116-9078-57a75f2d937a">| <img width="1067" alt="image" src="https://github.com/axelarnetwork/axelarjs/assets/78221556/9792abaa-6509-41c3-8c5b-a7434c24dc10"> |

chore: Improve the clarity that user can change the chain

---

apps/maestro/src/config/env.ts
apps/maestro/src/lib/utils/gform.ts
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/index.tsx

This PR implements pre-filling the following fields in the Claim Token Ownership form:
- Token Type: Interchain Token Service (ITS)
- Token Address: With the deployed token address
- Origin Chain: The token's origin chain
- Target Chains: All chains where the token is deployed
Closes #326 [AXE-3655](https://axelarnetwork.atlassian.net/browse/AXE-3655)
[AXE-3655]: https://axelarnetwork.atlassian.net/browse/AXE-3655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: implement gform prefill

---

apps/maestro/src/lib/contracts/InterchainTokenService.abi.ts
apps/maestro/src/lib/contracts/InterchainTokenService.hooks.ts
apps/maestro/src/lib/contracts/TokenManager.abi.ts
apps/maestro/src/lib/contracts/TokenManager.hooks.ts
packages/evm/package.json
packages/evm/src/contracts/its/IInterchainTokenService/IInterchainTokenService.abi.ts
packages/evm/src/contracts/its/ITokenManager/ITokenManager.abi.ts
packages/evm/src/contracts/its/ITokenManager/ITokenManager.args.ts
packages/evm/src/contracts/its/InterchainTokenService/InterchainTokenService.abi.ts
packages/evm/src/contracts/its/TokenManager/TokenManager.abi.ts
packages/evm/src/contracts/its/TokenManager/TokenManager.args.ts
pnpm-lock.yaml

Linked Jira Ticket: [AXE-3543](https://axelarnetwork.atlassian.net/browse/AXE-3543)
This PR updates the `@axelar-network/interchain-token-service` package to `1.2.4` and follow the guide [here](https://github.com/axelarnetwork/axelarjs/tree/main/packages/evm#guides) to generate new contract abis and types.
[AXE-3543]: https://axelarnetwork.atlassian.net/browse/AXE-3543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update ITS contracts to v1.2.4

---

apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

chore: update marketing form label

---

apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

chore: update squid link tooltip

---

apps/maestro/src/ui/pages/InterchainTokenDetailsPage/TokenDetailsSection.tsx

Add description mentioning that the image only show at ITS portal

chore: note that logo only work at its

---

.changeset/pink-kings-speak.md
.changeset/thin-ladybugs-attack.md

[AXE-3690](https://axelarnetwork.atlassian.net/browse/AXE-3690)
- feat: prefill claim token ownership form 
- chore: update axelarjs-sdk to 0.15.0 and pass executeData for more accurate gas estimation 
- chore: add report bug at the footer - chore: improve clarity in the root page that user can change the chain 
- chore: update axelar logo to improve branding prominence 
- chore: add provide liquidity button to dex for each chain in the token details page 
- chore: update ITS contracts to v1.2.4
Updated changes after ITS sync:
- chore: add note that logo only works at ITS portal https://github.com/axelarnetwork/axelarjs/pull/336
- chore: update squid link tooltip https://github.com/axelarnetwork/axelarjs/pull/335
- chore: update marketing form label …

docs(changeset): ITS dependency updates and UI/UX enhancements

---

apps/maestro/src/config/env.ts
apps/maestro/src/lib/utils/gform.ts
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/index.tsx

Closes #360
[AXL-3974](https://axelarnetwork.atlassian.net/browse/AXE-3974)
Prefill the token name and symbol as well in the format `Token Name (Token Symbol)`

chore: prefill token name and symbol

---

apps/maestro/src/features/SearchInterchainToken/SearchInterchainToken.tsx
apps/maestro/src/ui/components/EVMChainsDropdown/EVMChainsDropdown.tsx

Closes #347
[AXE-3803](https://axelarnetwork.atlassian.net/browse/AXE-3803)
Expands clickable area for 'Selected Chain' dropdown
[AXE-3803]: https://axelarnetwork.atlassian.net/browse/AXE-3803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: expand click areas for selected chain

---

apps/maestro/src/services/axelarscan/hooks.ts

Fix build error from wrong args passing to axelarscan apis

chore: fix wrong args passing to axelarscan apis

---

.changeset/quick-moles-push.md
apps/maestro/src/server/routers/gmp/getRecentTransactions.ts
packages/api/src/gmp/types.ts

Fix type error by make txHash optional in searchGMP api

chore: fix type error

---

apps/maestro/src/pages/_document.tsx

Include the provided twitter tracking script in the header of the app.
Please delete options that are not relevant.
Check that the script is included inside the header when running the application.

feat: add twitter conversion tracking base code

---

.changeset/eleven-clocks-deny.md
packages/api/src/axelar-query/client.spec.ts
packages/api/src/axelar-query/client.ts
packages/api/src/axelar-query/fee/getL1Fee.spec.ts
packages/api/src/axelar-query/isomorphic.ts

https://axelarnetwork.atlassian.net/browse/AXE-4444
Added missing functions from axelarjs sdk v1

feat: add denom and symbol conversion functions

---

.changeset/sour-crews-lie.md
apps/maestro/src/pages/_document.tsx

Configure and use consent management platform using Cookie-Script to address GDPR/CCPA compliance and resolve Google Analytics traffic issues for European users on interchain.axelar.dev.
Created the banner on the platform and added the script to our codebase.
Check that the banner is being shown and that the design is ok.

feat: add cookies consent banner

---

apps/maestro/src/config/evm-chains.ts

Fixed rpc issue on ethereum which blocks our partner to deploy token

chore: add additional rpc urls for eth

---

.changeset/beige-rings-live.md
.changeset/hot-cameras-retire.md
apps/axelarscan-amplifier-apis/CHANGELOG.md
apps/axelarscan-amplifier-apis/package.json
apps/maestro/CHANGELOG.md
apps/maestro/package.json
apps/maestro/src/config/evm-chains.ts

testnet release

---

apps/maestro/src/features/CanonicalTokenDeployment/CanonicalTokenDeployment.state.ts
apps/maestro/src/server/routers/gmp/getTransactionStatusOnDestinationChains.ts
apps/maestro/src/server/routers/gmp/getTransactionStatusesOnDestinationChains.ts
apps/maestro/src/services/axelarscan/hooks.ts
apps/maestro/src/services/gmp/hooks.ts
apps/maestro/src/ui/compounds/GMPTxStatusMonitor/GMPTxStatusMonitor.tsx
packages/api/src/gmp/types.ts

https://axelarnetwork.atlassian.net/browse/AXE-7180
This PR fixes the tx progress tracker to support multiple hops tx.

feat: fix tx progress for its hub tx

---

apps/maestro/src/features/CanonicalTokenDeployment/hooks/useDeployAndRegisterRemoteCanonicalTokenMutation.ts
apps/maestro/src/features/RegisterRemoteTokens/hooks/useRegisterRemoteCanonicalTokens.ts

This PR fixes the canonical cannot be deployed due to incorrect contract call after the upgrade

fix: remove originalChainName

---

apps/maestro/src/features/InterchainTokenList/RegisteredInterchainTokenCard.tsx
apps/maestro/src/services/interchainToken/hooks.ts

feat: add switch chain button in balance for incompatible chains

---

apps/maestro/src/features/InterchainTokenDeployment/InterchainTokenDeployment.state.ts
apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.tsx
apps/maestro/src/features/SendInterchainToken/hooks/useInterchainTransferMutation.ts
apps/maestro/src/features/suiHooks/useDeployToken.ts

feat: show user number of steps when deploying from sui

---

apps/maestro/src/server/routers/sui/index.ts

This PR commented out merge coins to fix transfer issue from sui to other chains
https://axelarnetwork.atlassian.net/browse/AXE-7774

chore(sui): fix sui transfer to other chain

---

apps/maestro/src/server/context.ts
apps/maestro/src/server/routers/interchainToken/recordInterchainTokenDeployment.ts
apps/maestro/src/server/utils.ts

https://axelarnetwork.atlassian.net/browse/AXE-7781
The error comes from db record for pre-deploy token where it can't find `sui` chain config.

chore: fix evm to sui deployment

---

apps/maestro/src/server/routers/axelarscan/getVMChainConfigs.ts
apps/maestro/src/services/axelarscan/hooks.ts
packages/evm/src/clients/clients.spec.ts
packages/transaction-recovery/src/manual-relay-to-dest-chain/lib/EvmGatewayApproveTx/txHelper.spec.ts

https://axelarnetwork.atlassian.net/browse/AXE-7804
This PR remove unused properties from chain object definition as the response from axelarscan api has changed and ITS failed to parse that.

refactor: simplify VM chain config schema and display name

---

apps/maestro/src/config/chains/evm-chains.ts
apps/maestro/src/config/chains/vm-chains.ts
apps/maestro/src/features/InterchainTokenDeployment/hooks/useDeployAndRegisterRemoteInterchainTokenMutation.ts
apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.tsx
apps/maestro/src/features/InterchainTokenDeployment/steps/review/Review.tsx
apps/maestro/src/features/RegisterRemoteTokens/RegisterRemoteTokens.tsx
apps/maestro/src/features/RegisterRemoteTokens/hooks/useRegisterRemoteInterchainTokenOnSui.ts
apps/maestro/src/features/RegisterRemoteTokens/hooks/useRegisterRemoteInterchainTokens.ts
apps/maestro/src/features/SendInterchainToken/SendInterchainToken.tsx
apps/maestro/src/features/SendInterchainToken/hooks/useInterchainTransferMutation.ts
apps/maestro/src/features/suiHooks/useDeployToken.ts
apps/maestro/src/server/routers/axelarjsSDK/getChainInfo.ts
apps/maestro/src/server/routers/gmp/getTransactionStatusOnDestinationChains.ts
apps/maestro/src/server/routers/gmp/getTransactionStatusesOnDestinationChains.ts
apps/maestro/src/server/routers/interchainToken/getInterchainTokenDetails.ts
apps/maestro/src/server/routers/interchainToken/recordInterchainTokenDeployment.ts
apps/maestro/src/server/routers/interchainToken/recordRemoteTokensDeployment.ts
apps/maestro/src/server/routers/interchainToken/searchInterchainToken.ts
apps/maestro/src/server/routers/sui/index.ts
apps/maestro/src/server/routers/sui/utils/txUtils.ts
apps/maestro/src/server/routers/sui/utils/utils.ts
apps/maestro/src/services/axelarscan/hooks.ts
apps/maestro/src/services/db/postgres/MaestroPostgresClient.ts
apps/maestro/src/services/gmp/hooks.ts
apps/maestro/src/ui/compounds/GMPTxStatusMonitor/GMPTxStatusMonitor.tsx
apps/maestro/src/ui/pages/InterchainTokenDetailsPage/ConnectedInterchainTokensPage.tsx

- Fixed the remote chain doesn't move into pending state immediately for 2-hops tx: https://axelarnetwork.atlassian.net/browse/AXE-7782
- Fixed the remote chain doesn't move into registered state for 2-hops tx: https://axelarnetwork.atlassian.net/browse/AXE-7782
- Fixed cannot record token to the db when the remote chain is sui and source chain is evm: https://axelarnetwork.atlassian.net/browse/AXE-7954
- Fixed hardcoded fee for some sui txs: https://axelarnetwork.atlassian.net/browse/AXE-7955
- Fixed the `Deploy Token` button randomly stuck loading forever https://axelarnetwork.atlassian.net/browse/AXE-7975
- Fixed sui chain id changes from `sui` to `sui-2` c0b7254 https://axelarnetwork.atlassian.net/browse/AXE-7983
- Fixed gas paid incorrectly from sui to other chains …

chore: improve ux after deployment in token details page

---

apps/maestro/src/features/InterchainTokenDeployment/steps/deploy-and-register/DeployAndRegister.tsx
apps/maestro/src/features/RegisterRemoteTokens/RegisterRemoteTokens.tsx
apps/maestro/src/server/routers/axelarjsSDK/getChainInfo.ts
apps/maestro/src/server/routers/axelarscan/getVMChainConfigs.ts
apps/maestro/src/server/routers/gmp/getTransactionStatusOnDestinationChains.ts
apps/maestro/src/server/routers/interchainToken/getInterchainTokenBalanceForOwner.ts
apps/maestro/src/server/routers/interchainToken/getInterchainTokenDetails.ts
apps/maestro/src/server/routers/interchainToken/recordRemoteTokensDeployment.ts
apps/maestro/src/server/routers/sui/index.ts
apps/maestro/src/server/routers/sui/utils/txUtils.ts
apps/maestro/src/server/routers/sui/utils/utils.ts
apps/maestro/src/services/axelarscan/hooks.ts
packages/api/src/axelar-config/types.ts
packages/evm/src/clients/clients.spec.ts

This PR resolves conflicts to main branch for devnet-amplifier
other minor changes:
- Fixed sui-2 hardcoded https://axelarnetwork.atlassian.net/browse/AXE-8036
- Refactor chain config https://axelarnetwork.atlassian.net/browse/AXE-8063

chore: prepare testnet merge for devnet-amplifier

---

apps/maestro/src/server/routers/sui/index.ts

handle the custom minter address for distributor role

chore: handle minter address correctly

---

apps/maestro/src/ui/layouts/Page.tsx

Make the token details page looks similar to testnet

fix: ui issue in the token details page

---

apps/maestro/src/ui/components/ChainsDropdown/ChainsDropdown.tsx

chore: include healthcheck inside dropdown button

---

apps/maestro/src/config/chains/evm-chains.ts

feat: xrpl evm mainnet

---

apps/maestro/src/config/chains/evm-chains.ts
packages/README.md
packages/evm/src/clients/mainnet-client.ts
packages/evm/src/clients/testnet-client.ts

chore: add berachain

---

apps/maestro/.env.example
apps/maestro/README.md

**Description**
This PR aims to enhance the experience of new developers who want to set-up the project.
- Add all necessary setup and build instructions to README.
- Add section about database migrations.
- Add section about setting up Neon & Redis and configuring their env vars.
- Add links to all existing READMEs at the Docs section, and document all commands of package.json.
- Update `.env.example` to make it clearer to read and modify.
- Remove all unused vars from it, and add all the necessary ones with placeholder values if needed.

chore: Improve README and .env.example

---

apps/maestro/src/features/InterchainTokenDeployment/hooks/useDeployAndRegisterRemoteInterchainTokenMutation.ts
apps/maestro/src/features/RegisterRemoteTokens/hooks/useRegisterRemoteInterchainTokens.ts
apps/maestro/src/lib/utils/gas.ts

**Description**
- Move `scaleGasValue` to a util file.
- Use `scaleGasValue` in `useRegisterRemoteInterchainTokens`.

Implement Remote Token Deployment
